$wshell = New-Object -ComObject wscript.shell;
$wshell.SendKeys("+^%{F6}")
sleep(1)
$wshell.SendKeys("password")
$wshell.SendKeys("~")
sleep(1)
$wshell.SendKeys("%n")
$wshell.SendKeys("%R")
$wshell.SendKeys("~")
$wshell.SendKeys("~")
