version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: veltisql
    ports:
      - "5432:5432"
    networks: 
      - main
  web:
    build: .
    command: ./run.sh
    volumes:
      - .:/webapps
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks: 
      - main
networks: 
  main: